version: '3.8'
services:
  server:
    build:
      context: ./GGY
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db

  web:
    build:
      context: ./ggy-ui
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
